### PR TITLE
empirical p-value, performance table, README, feature_importance and permutation_importance

### PR DESCRIPTION
**Pull request by danielmlow**
1. Empirical p-value for permutation test
2. Outputs Performance tables both reflecting plots as well as summarized with 95% CI 
3. Expanded README 
4. feature_importance and permutation_importance are only working for linear models. have not fully tested with hyperparameter tuning or complex pipelines. Detailed this in the README. They are saved in the pkl file, but I should also output something similar to SHAP.

### CODE REVIEW

**Comment by satra** [comment]
@danielmlow - this seems to include a  lot of unrelated files. can you send a PR that only includes the relevant changes?

**Comment by danielmlow** [comment]
> @danielmlow - this seems to include a lot of unrelated files. can you send a PR that only includes the relevant changes?

Yeah, I left those on purpose. For people trying to use this package, I think it will be much more clear what they'll obtain if we include a few `out-` folders. If not it's too abstract (e.g., when we say we're comparing models, outputing feature importance, etc). I would leave them. But up to you :)

**Comment by satra** [comment]
the short example should be very easy for people to run. so i would remove the outputs for now.

**Comment by danielmlow** [comment]
True. But they may not decide to clone it and run it without seeing what it
would look like. So maybe we leave one?

**Comment by satra** [comment]
then you extract things and add figures to the readme. the output folder contains a lot of things. i don't think they should be in the repo other than for testing purpose. this PR adds/changes 124 files. if an output folder needs to be kept it has to be minimal.

**Comment by danielmlow** [comment]
Will re-do without output directory examples and instead include example images in the README

**Pull request closed without merging**
